// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSK_A_VZLvx5Q5aVu5kMcZHrddtwa1vCs',
    appId: '1:137259691446:web:757663a999fb1dfadf6517',
    messagingSenderId: '137259691446',
    projectId: 'my-notes-cyprian',
    authDomain: 'my-notes-cyprian.firebaseapp.com',
    storageBucket: 'my-notes-cyprian.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpYzuEpxYcq-ETn6-LOstp0COiRsweuAc',
    appId: '1:137259691446:android:9b7644a93251c0a5df6517',
    messagingSenderId: '137259691446',
    projectId: 'my-notes-cyprian',
    storageBucket: 'my-notes-cyprian.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkxJc1KaZe7DvMK48izT0q9mB9ZeiSrbk',
    appId: '1:137259691446:ios:fab8631fd4640e25df6517',
    messagingSenderId: '137259691446',
    projectId: 'my-notes-cyprian',
    storageBucket: 'my-notes-cyprian.appspot.com',
    iosClientId: '137259691446-597thsdmhe33mblcddnpmt6smecirto8.apps.googleusercontent.com',
    iosBundleId: 'com.example.mynotes',
  );
}
